<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.yggdrasil-labs</groupId>
        <artifactId>mimir-boot-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../mimir-boot-parent/pom.xml</relativePath>
    </parent>

    <artifactId>mimir-boot-starters</artifactId>
    <packaging>pom</packaging>

    <name>Mimir Boot Starters</name>
    <description>Mimir Boot Starter 集合模块，包含日志、异常处理、Web、MyBatis、Nacos 配置加密、测试等启动器</description>
    <url>https://github.com/Yggdrasil-Labs/mimir-boot</url>

    <modules>
        <module>mimir-boot-starter-log</module>
        <module>mimir-boot-starter-exception</module>
        <module>mimir-boot-starter-web</module>
        <module>mimir-boot-starter-mybatis</module>
        <module>mimir-boot-starter-mybatis-processor</module>
        <module>mimir-boot-starter-nacos</module>
        <module>mimir-boot-starter-test</module>
        <module>mimir-boot-starter-rpc-core</module>
        <module>mimir-boot-starter-dubbo</module>
        <module>mimir-boot-starter-feign</module>
    </modules>
</project>
